### ISSUE TITLE
Question regarding HA setup of switch

### ISSUE THREAD

**Issue by WoodsterDK** [monster1025/aqara-mqtt#5]
Hi there,
Do you have an example of configuring the switch as a input withou coupling it to a automation directly.
Is it possible to assign a friendly name to each each type of click?

**Comment by WoodsterDK** [comment]
And what about the sensor battery level - how do you handle that?

**Comment by monster1025** [comment]
Here is battery level sensor example:
```
sensors:
- platform: mqtt
  state_topic: 'home/switch/bath/status'
  name: 'switch_bath_voltage'
  value_template: "{{ (100-((3300 - float(value)) / (3300 - 2800)) * 100) | round(0) }}"
  unit_of_measurement: '%'
```

> Do you have an example of configuring the switch as a input withou coupling it to a automation directly, this is only one method to handle 'events' (not state change) that I know in HA (but my skills in HA are not so good =) ).
I am using it as it specified in README:
```
trigger:
    platform: mqtt
    topic: home/switch/hall/status
    payload: 'click'
action:
  service: script.hall_force_light_on
```
